CREATE TABLE IF NOT EXISTS clients
(
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY UNIQUE,
    name varchar(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS client_phones
(
    id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY UNIQUE,
    number_phone VARCHAR(20) NOT NULL UNIQUE,
    client_id BIGINT NOT NULL,

    CONSTRAINT fk_client_id FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS client_emails
(
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY UNIQUE,
    email VARCHAR(64) NOT NULL UNIQUE,
    client_id BIGINT NOT NULL,

    CONSTRAINT fk_client_id FOREIGN KEY(client_id) REFERENCES clients(id) ON DELETE CASCADE
);
